import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Fira_Sans } from 'next/font/google';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const firaSans = Fira_Sans({
  subsets: ['latin'],
  display: 'auto',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Adithya Anandsaikrishnan',
  description: 'Generated by create next app',
};

const currentTheme = 'retro';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme={currentTheme} lang="en">
      <body className={`${firaSans.className} antialiased`}>{children}</body>
    </html>
  );
}
